import { Type } from 'typebox';
import type { ErrorCategory } from './common-schemas.js';

/** Closed enumeration of M1Interface 3.4; each code has exactly one category. */
export const REASON_CODE_CATEGORY = {
  INVALID_REQUEST: 'VALIDATION',
  CALLER_FORBIDDEN: 'POLICY',
  RUN_NOT_FOUND: 'VALIDATION',
  RUN_BLOCKED: 'CONFLICT',
  REQUEST_CONFLICT: 'CONFLICT',
  RUN_LIMIT: 'CONFLICT',
  REPOSITORY_INVALID: 'VALIDATION',
  DEFINITION_MISMATCH: 'INTEGRITY',
  DEFINITION_UNAVAILABLE: 'DEPENDENCY',
  AGENT_RUN_ACTIVE: 'CONFLICT',
  AGENT_RUN_EXISTS: 'CONFLICT',
  AGENT_RUN_NOT_FOUND: 'VALIDATION',
  AGENT_RUN_ENDED: 'CONFLICT',
  FORBIDDEN: 'POLICY',
  UNSUPPORTED_CAPABILITY: 'CONTRACT',
  INVALID_INPUT: 'VALIDATION',
  QUESTION_NOT_PENDING: 'CONFLICT',
  INVALID_ARTIFACT_REF: 'VALIDATION',
  USER_DECLINED: 'POLICY',
  BUDGET_WRAP_UP: 'RESOURCE',
  BUDGET_EXHAUSTED: 'RESOURCE',
  FINAL_CALL_USED: 'RESOURCE',
  OUT_OF_SCOPE: 'POLICY',
  NOT_FOUND: 'EXECUTION',
  UNSUPPORTED_FILE: 'EXECUTION',
  INVALID_RANGE: 'VALIDATION',
  INVALID_QUERY: 'VALIDATION',
  LIMIT_EXCEEDED: 'RESOURCE',
  PROVIDER_UNREACHABLE: 'DEPENDENCY',
  PROVIDER_RATE_LIMITED: 'DEPENDENCY',
  PROVIDER_AUTH: 'DEPENDENCY',
  PROVIDER_ERROR: 'DEPENDENCY',
  UNIT_TIMEOUT: 'TIMEOUT',
  INTERNAL: 'INTERNAL',
  EXECUTION_CANCELLED: 'EXECUTION',
  SCOPE_MISSING: 'INTEGRITY',
  PATH_ESCAPE: 'INTEGRITY',
  GUARD_FAILURE: 'INTEGRITY',
  EXECUTION_STOP_UNCONFIRMED: 'INTERNAL',
  PIN_FAILED: 'DEPENDENCY',
  WORKFLOW_INTERNAL: 'INTERNAL',
  KERNEL_INTERNAL: 'INTERNAL',
} as const satisfies Record<string, ErrorCategory>;

export type ReasonCode = keyof typeof REASON_CODE_CATEGORY;
export const REASON_CODES = Object.keys(REASON_CODE_CATEGORY) as ReasonCode[];
export const ReasonCodeSchema = Type.Unsafe<ReasonCode>(
  Type.Enum(REASON_CODES, { $id: 'platform.common.ReasonCode.v0' }),
);

/** Reason codes that may appear in a SyscallRejected. */
export const SYSCALL_REJECTED_CODES = [
  'INVALID_REQUEST',
  'CALLER_FORBIDDEN',
  'RUN_NOT_FOUND',
  'RUN_BLOCKED',
  'REQUEST_CONFLICT',
  'RUN_LIMIT',
  'REPOSITORY_INVALID',
  'DEFINITION_MISMATCH',
  'DEFINITION_UNAVAILABLE',
  'AGENT_RUN_ACTIVE',
  'AGENT_RUN_EXISTS',
  'AGENT_RUN_NOT_FOUND',
  'AGENT_RUN_ENDED',
  'FORBIDDEN',
  'UNSUPPORTED_CAPABILITY',
  'INVALID_INPUT',
  'QUESTION_NOT_PENDING',
  'INVALID_ARTIFACT_REF',
] as const satisfies readonly ReasonCode[];

/** Reason codes that may appear in a UnitReport, and therefore in a failurePolicy. */
export const UNIT_REPORT_CODES = [
  'INVALID_INPUT',
  'INVALID_ARTIFACT_REF',
  'USER_DECLINED',
  'BUDGET_WRAP_UP',
  'BUDGET_EXHAUSTED',
  'FINAL_CALL_USED',
  'OUT_OF_SCOPE',
  'NOT_FOUND',
  'UNSUPPORTED_FILE',
  'INVALID_RANGE',
  'INVALID_QUERY',
  'LIMIT_EXCEEDED',
  'PROVIDER_UNREACHABLE',
  'PROVIDER_RATE_LIMITED',
  'PROVIDER_AUTH',
  'PROVIDER_ERROR',
  'UNIT_TIMEOUT',
  'INTERNAL',
] as const satisfies readonly ReasonCode[];
